# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d8175bddf044045ca9b9355ce2e5d65f249e4053d137a4d801a1f698f7e9f1cce823a62f6a15677c7b40c3c5f49bfa2f0e419128ab8c160865609817e39f4a

test:
  secret_key_base: 6823645c98aebfda35409f63775de6bd802468bb133704485b4afb31994d98e4b829ef9aab1d77a1760432ed6f7dfa85ffb6036f67f61f0c984bf7ade9247b89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
